export const services = [
  {
    category: "Electrician",
    subcategories: [
      "General Electrical Repairs",
      "AC Repair and Installation",
      "Electrical Panel Upgrades",
      "Smart Home Wiring",
      "Emergency Electrical Services",
      "Solar Panel Installation",
      "Generator Installation",
      "Home Theater Wiring",
      "Electrical Safety Inspection",
      "Circuit Breaker Installation",
      "Lighting Installation",
      "Outlet and Switch Installation",
      "Ceiling Fan Installation",
      "Wiring and Rewiring",
      "Electrical Appliance Repair",
      "Load Shedding Solutions",
      "UPS Installation",
      "Inverter Installation",
      "Street Light Installation",
      "Voltage Stabilizer Installation",
    ],
  },
  {
    category: "Plumber",
    subcategories: [
      "Leak Detection and Repair",
      "Pipe Replacement",
      "Bathroom Plumbing Fixtures",
      "Water Tank Installation",
      "Septic Tank Cleaning",
      "Gas Pipe Installation",
      "Sump Pump Installation",
      "Hydro Jetting",
      "Bathroom Waterproofing",
      "Drain Cleaning",
      "Toilet Repair",
      "Faucet Repair",
      "Sewer Line Services",
      "Water Heater Repair",
      "Pipe Insulation",
      "Underground Water Tank Cleaning",
      "Overhead Tank Installation",
      "Water Motor Repair",
      "Geyser Installation",
      "Kitchen Sink Installation",
      "Bathroom Renovation",
      "Water Pump Installation",
    ],
  },
  {
    category: "Carpenter",
    subcategories: [
      "Custom Furniture Design",
      "Kitchen Cabinet Installation",
      "Wooden Flooring Installation",
      "Deck Construction",
      "Door Frame Repair",
      "Staircase Installation",
      "Wood Paneling",
      "Shelving Installation",
      "Furniture Restoration",
      "Wardrobe Installation",
      "Furniture Assembly",
      "Window Frame Repair",
      "Furniture Repair",
      "Wooden Fence Installation",
      "Office Furniture Installation",
    ],
  },
  {
    category: "Painter",
    subcategories: [
      "Interior Painting",
      "Exterior Painting",
      "Wall Texturing",
      "Wallpaper Installation",
      "Spray Painting",
      "Fence Painting",
      "Decorative Painting",
      "Epoxy Floor Coating",
      "Commercial Painting",
      "Faux Finishing",
      "Paint Removal",
      "Graffiti Removal",
      "Rust Proofing",
      "Eco-Friendly Painting",
      "Industrial Coatings",
    ],
  },
  {
    category: "Cleaning Services",
    subcategories: [
      "Home Deep Cleaning",
      "Carpet Cleaning",
      "Sofa Cleaning",
      "Office Cleaning",
      "Window Cleaning",
      "Pest Control",
      "Post-Construction Cleaning",
      "Move-in/Move-out Cleaning",
      "Pressure Washing",
      "Air Duct Cleaning",
      "Mattress Cleaning",
      "Pool Cleaning",
      "Curtain Cleaning",
      "Hoarding Cleanup",
      "Solar Panel Cleaning",
    ],
  },
  {
    category: "AC Technician",
    subcategories: [
      "AC Installation",
      "AC Repair",
      "AC Gas Refilling",
      "AC Maintenance",
      "Split AC Servicing",
      "Window AC Repair",
      "Thermostat Repair",
      "Ductless Mini-Split Installation",
      "Commercial AC Servicing",
      "Refrigerant Charging",
      "AC Filter Replacement",
      "AC Compressor Repair",
      "Emergency AC Repair",
      "AC Duct Cleaning",
      "AC Insulation Services",
    ],
  },
  {
    category: "Home Appliance Repair",
    subcategories: [
      "Refrigerator Repair",
      "Washing Machine Repair",
      "Microwave Repair",
      "Oven Repair",
      "Dishwasher Repair",
      "Dryer Repair",
      "Vacuum Cleaner Repair",
      "Coffee Machine Repair",
      "Blender Repair",
      "Toaster Repair",
      "Ice Maker Repair",
      "Home Theater Repair",
      "Fan Repair",
      "Water Purifier Repair",
      "Stove Repair",
    ],
  },
  {
    category: "Gardening & Landscaping",
    subcategories: [
      "Lawn Mowing",
      "Hedge Trimming",
      "Garden Design",
      "Tree Trimming",
      "Irrigation System Installation",
      "Planting Services",
      "Garden Pest Control",
      "Soil Fertilizing",
      "Garden Lighting",
      "Water Feature Installation",
      "Garden Pathway Construction",
      "Seasonal Planting",
      "Garden Waste Removal",
      "Garden Cleanup",
      "Landscape Consultation",
    ],
  },
  {
    category: "Roofing & Waterproofing",
    subcategories: [
      "Roof Repair",
      "Roof Replacement",
      "Waterproofing Services",
      "Gutter Cleaning",
      "Chimney Repair",
      "Skylight Installation",
      "Flashing Repair",
      "Balcony Waterproofing",
      "Flat Roof Repair",
      "Shingle Replacement",
      "Roof Inspection",
      "Roof Cleaning",
      "Insulation Installation",
      "Leak Repair",
      "Roof Coating",
    ],
  },
  {
    category: "Security Services",
    subcategories: [
      "CCTV Installation",
      "Alarm System Installation",
      "Security Guard Services",
      "Access Control Systems",
      "Biometric Systems",
      "Fire Alarm Installation",
      "Security Patrol Services",
      "Intercom Systems",
      "Motion Detector Installation",
      "Video Door Phone Installation",
      "Security System Maintenance",
      "Security Consultancy",
      "Security System Repair",
      "Access Card Setup",
      "Security Lighting Installation",
    ],
  },
  {
    category: "Laundry & Dry Cleaning",
    subcategories: [
      "Clothes Washing",
      "Dry Cleaning",
      "Ironing and Pressing",
      "Shoe Cleaning",
      "Curtain Cleaning",
      "Carpet Cleaning",
      "Leather Cleaning",
      "Blanket Cleaning",
      "Uniform Cleaning",
      "Stain Removal",
      "Delicate Fabric Care",
      "Alterations & Repairs",
      "Pick-up and Delivery",
      "Wedding Dress Cleaning",
      "Upholstery Cleaning",
    ],
  },
  {
    category: "Moving & Packing",
    subcategories: [
      "Local Moving",
      "Long-distance Moving",
      "Packing Services",
      "Unpacking Services",
      "Furniture Disassembly",
      "Furniture Assembly",
      "Storage Services",
      "Vehicle Transport",
      "Office Moving",
      "Fragile Item Handling",
      "Heavy Lifting",
      "Loading and Unloading",
      "International Moving",
      "Moving Supplies",
      "Disposal Services",
    ],
  },
  {
    category: "Pest Control",
    subcategories: [
      "Termite Treatment",
      "Bed Bug Extermination",
      "Mosquito Control",
      "Rodent Control",
      "Cockroach Treatment",
      "Ant Control",
      "Flea Control",
      "Spider Control",
      "Bee Removal",
      "Bird Control",
      "Pest Inspection",
      "Commercial Pest Control",
      "Organic Pest Control",
      "Pest Prevention",
      "Wasp Nest Removal",
    ],
  },
  {
    category: "Home Remodeling & Renovation",
    subcategories: [
      "Kitchen Remodeling",
      "Bathroom Renovation",
      "Flooring Installation",
      "Wall Partition",
      "False Ceiling",
      "Plumbing Renovation",
      "Electrical Renovation",
      "Painting and Decorating",
      "Tile Installation",
      "Cabinet Installation",
      "Door Replacement",
      "Window Replacement",
      "Basement Renovation",
      "Room Additions",
      "Outdoor Patio Construction",
    ],
  },
  {
    category: "HVAC Services",
    subcategories: [
      "Heating System Installation",
      "Heating System Repair",
      "Ventilation Cleaning",
      "Duct Installation",
      "Duct Repair",
      "HVAC Maintenance",
      "Thermostat Installation",
      "Furnace Repair",
      "Heat Pump Services",
      "Boiler Repair",
      "Indoor Air Quality Testing",
      "Energy Efficient Upgrades",
      "Commercial HVAC Services",
      "HVAC System Replacement",
      "Air Purifier Installation",
    ],
  },
  {
    category: "Interior Designing",
    subcategories: [
      "Space Planning",
      "Furniture Selection",
      "Lighting Design",
      "Color Consultation",
      "Window Treatments",
      "Flooring Selection",
      "Wall Decor",
      "Kitchen Design",
      "Bathroom Design",
      "Home Office Design",
      "Custom Furniture Design",
      "Storage Solutions",
      "Children's Room Design",
      "Home Staging",
      "Outdoor Living Space Design",
    ],
  },
  {
    category: "Appliance Installation",
    subcategories: [
      "Water Heater Installation",
      "Dishwasher Installation",
      "Oven Installation",
      "Ceiling Fan Installation",
      "Exhaust Fan Installation",
      "Washing Machine Installation",
      "Refrigerator Installation",
      "Microwave Installation",
      "Garbage Disposal Installation",
      "Dryer Installation",
      "Air Conditioner Installation",
      "Home Theater Setup",
      "Security Device Installation",
      "Smart Home Device Setup",
      "Solar Water Heater Installation",
    ],
  },
  {
    category: "Fitness & Health at Home",
    subcategories: [
      "Personal Training",
      "Yoga Instruction",
      "Massage Therapy",
      "Physiotherapy",
      "Nutrition Consultation",
      "Pilates Instruction",
      "Meditation Coaching",
      "Home Gym Setup",
      "Posture Correction",
      "Weight Loss Coaching",
      "Strength Training",
      "Cardio Training",
      "Injury Rehabilitation",
      "Senior Fitness",
      "Sports Coaching",
    ],
  },
  {
    category: "Technology & IT Support",
    subcategories: [
      "Computer Repair",
      "Printer Setup",
      "Network Setup",
      "Virus Removal",
      "Data Recovery",
      "Software Installation",
      "Hardware Upgrade",
      "Wi-Fi Optimization",
      "Smart Home Installation",
      "TV Mounting",
      "Home Theater Setup",
      "Security Software Setup",
      "Cloud Backup Setup",
      "Email Setup",
      "IT Consultation",
    ],
  },
  {
    category: "Pet Care",
    subcategories: [
      "Pet Grooming",
      "Veterinary Services",
      "Pet Sitting",
      "Dog Walking",
      "Pet Training",
      "Pet Boarding",
      "Pet Vaccination",
      "Pet Nutrition Consultation",
      "Pet Taxi",
      "Pet Bathing",
      "Pet Dental Care",
      "Pet Behavior Counseling",
      "Exotic Pet Care",
      "Pet Adoption Services",
      "Emergency Pet Care",
    ],
  },
  {
    category: "Event & Party Services",
    subcategories: [
      "Catering",
      "Photography",
      "Decoration",
      "DJ Services",
      "Tent Rental",
      "Chair and Table Rental",
      "Event Planning",
      "Sound System Setup",
      "Lighting Setup",
      "Video Recording",
      "Cake Design",
      "Invitation Design",
      "Security for Events",
      "Cleaning After Events",
      "Makeup and Hair Styling",
    ],
  },
  {
    category: "Automotive Services at Home",
    subcategories: [
      "Car Wash",
      "Car Detailing",
      "Minor Repairs",
      "Battery Replacement",
      "Tire Change",
      "Oil Change",
      "Car Polishing",
      "Engine Diagnostics",
      "Windshield Repair",
      "Headlight Restoration",
      "Brake Service",
      "Air Conditioning Service",
      "Car Interior Cleaning",
      "Fluid Top-Up",
      "Vehicle Inspection",
    ],
  },
  {
    category: "Tutoring & Education",
    subcategories: [
      "Language Tutoring",
      "Music Lessons",
      "Math Tutoring",
      "Science Tutoring",
      "Computer Lessons",
      "Exam Preparation",
      "Reading and Writing",
      "Art Lessons",
      "Dance Lessons",
      "Homework Help",
      "Test Taking Strategies",
      "Study Skills Coaching",
      "College Admissions Counseling",
      "Special Needs Tutoring",
      "Online Tutoring",
    ],
  },
  {
    category: "Legal & Financial Services",
    subcategories: [
      "Notary Services",
      "Tax Consultation",
      "Legal Advice",
      "Insurance Consulting",
      "Will Preparation",
      "Contract Drafting",
      "Business Registration",
      "Property Law Services",
      "Family Law Services",
      "Immigration Assistance",
      "Debt Counseling",
      "Investment Advice",
      "Loan Consulting",
      "Audit Services",
      "Mediation Services",
    ],
  },
  {
    category: "Miscellaneous",
    subcategories: [
      "Courier & Delivery",
      "Errand Running",
      "Personal Shopping",
      "Handyman Services",
      "Appliance Recycling",
      "Furniture Disposal",
      "Key Cutting",
      "Locksmith Services",
      "Custom Gifts",
      "Language Translation",
      "Meditation Coaching",
      "Personal Assistant",
      "Mobile Car Wash",
      "Recycling Pickup",
      "Volunteer Coordination",
    ],
  },
  {
    category: "Tailor & Stitching (Darzi)",
    subcategories: [
      "Men's Shalwar Kameez Stitching",
      "Women's Shalwar Kameez Stitching",
      "Bridal Dress Stitching",
      "Groom Dress Stitching",
      "Kids Dress Stitching",
      "Alteration Services",
      "Embroidery Work",
      "Shirt Stitching",
      "Trouser Stitching",
      "Suit Stitching",
      "Lehenga Stitching",
      "Saree Blouse Stitching",
      "School Uniform Stitching",
      "Curtain Stitching",
      "Cushion Cover Stitching",
      "Fancy Dress Design",
      "Party Wear Stitching",
      "Winter Coat Stitching",
      "Traditional Dress Stitching",
      "Custom Design Services",
    ],
  },
  {
    category: "Beauty & Salon Services",
    subcategories: [
      "Bridal Makeup",
      "Party Makeup",
      "Hair Styling",
      "Hair Cutting (Women)",
      "Hair Coloring",
      "Mehendi/Henna Application",
      "Facial Treatment",
      "Manicure & Pedicure",
      "Threading",
      "Waxing",
      "Hair Straightening",
      "Hair Spa",
      "Bleaching",
      "Nail Art",
      "Eyelash Extensions",
      "Eyebrow Shaping",
      "Bridal Package",
      "Skin Treatment",
      "Hair Rebonding",
      "Keratin Treatment",
    ],
  },
  {
    category: "Barber Services",
    subcategories: [
      "Haircut",
      "Beard Trim",
      "Shaving",
      "Hair Styling (Men)",
      "Hair Coloring (Men)",
      "Facial (Men)",
      "Head Massage",
      "Kids Haircut",
      "Traditional Shave",
      "Beard Design",
      "Hair Wash",
      "Eyebrow Threading (Men)",
      "Hair Treatment",
      "Scalp Treatment",
      "Wedding Grooming",
    ],
  },
  {
    category: "Construction & Masonry",
    subcategories: [
      "Bricklaying",
      "Plastering",
      "Tile Installation",
      "Marble Installation",
      "Concrete Work",
      "Foundation Work",
      "Wall Construction",
      "Boundary Wall Construction",
      "Roof Casting",
      "Floor Leveling",
      "Renovation Work",
      "Extension Work",
      "Demolition Services",
      "Stone Masonry",
      "Gypsum Work",
      "POP Ceiling",
      "Railing Installation",
      "Staircase Construction",
      "Balcony Construction",
      "Pillar Construction",
    ],
  },
  {
    category: "Welding & Fabrication",
    subcategories: [
      "Iron Gate Welding",
      "Grills Welding",
      "Steel Structure Welding",
      "Railing Welding",
      "Water Tank Stand Welding",
      "Gate Repair",
      "Metal Furniture Welding",
      "Car Parking Shed",
      "Aluminum Welding",
      "Stainless Steel Welding",
      "Pipeline Welding",
      "Iron Door Welding",
      "Shed Construction",
      "Canopy Installation",
      "Metal Fabrication",
    ],
  },
  {
    category: "Mobile & Electronics Repair",
    subcategories: [
      "Mobile Screen Replacement",
      "Mobile Battery Replacement",
      "Mobile Software Issues",
      "Mobile Water Damage Repair",
      "Mobile Charging Port Repair",
      "Tablet Repair",
      "Laptop Repair",
      "Computer Repair",
      "Gaming Console Repair",
      "Smartwatch Repair",
      "Earphone Repair",
      "Speaker Repair",
      "Camera Repair",
      "Power Bank Repair",
      "Accessories Sales",
    ],
  },
  {
    category: "Motorcycle & Bike Services",
    subcategories: [
      "Bike Wash",
      "Engine Repair",
      "Oil Change",
      "Tire Replacement",
      "Brake Repair",
      "Battery Replacement",
      "Chain Cleaning",
      "Bike Polishing",
      "Carburetor Cleaning",
      "Puncture Repair",
      "Electrical Repair",
      "Bike Modification",
      "Suspension Repair",
      "Clutch Repair",
      "Full Service",
    ],
  },
  {
    category: "Rickshaw Services",
    subcategories: [
      "Rickshaw Ride",
      "Delivery Service",
      "Goods Transport",
      "Furniture Moving",
      "Local Transport",
      "Pickup Service",
      "Drop-off Service",
      "Hourly Rental",
      "Multiple Stops Service",
      "Heavy Items Transport",
    ],
  },
  {
    category: "Home Chef & Tiffin Services",
    subcategories: [
      "Daily Tiffin Service",
      "Party Catering",
      "Wedding Catering",
      "BBQ Catering",
      "Biryani Specialist",
      "Karahi Specialist",
      "Traditional Food",
      "Chinese Food",
      "Fast Food",
      "Breakfast Service",
      "Diet Food",
      "Lunch Tiffin",
      "Dinner Tiffin",
      "Monthly Tiffin Package",
      "Weekly Tiffin Package",
    ],
  },
  {
    category: "House Help & Maid Services",
    subcategories: [
      "Full-time Maid",
      "Part-time Maid",
      "Cooking",
      "Cleaning & Sweeping",
      "Dish Washing",
      "Laundry",
      "Ironing",
      "Child Care",
      "Elderly Care",
      "Patient Care",
      "Live-in Maid",
      "Daily Maid",
      "Weekend Maid",
      "Emergency Cleaning",
      "Deep Cleaning",
    ],
  },
  {
    category: "Driver Services",
    subcategories: [
      "Personal Driver",
      "Office Driver",
      "Family Driver",
      "Part-time Driver",
      "Full-time Driver",
      "Wedding Driver",
      "Event Driver",
      "Night Driver",
      "Long Distance Driver",
      "Temporary Driver",
      "Chauffeur Service",
      "Female Driver",
      "School Pick & Drop",
      "Office Pick & Drop",
      "Airport Transfer",
    ],
  },
  {
    category: "Photography & Videography",
    subcategories: [
      "Wedding Photography",
      "Wedding Videography",
      "Pre-Wedding Shoot",
      "Birthday Photography",
      "Event Photography",
      "Product Photography",
      "Real Estate Photography",
      "Portrait Photography",
      "Fashion Photography",
      "Drone Photography",
      "Video Editing",
      "Photo Editing",
      "Documentary Making",
      "Corporate Videos",
      "YouTube Content Creation",
    ],
  },
  {
    category: "Printing & Graphics",
    subcategories: [
      "Visiting Card Printing",
      "Wedding Card Printing",
      "Flyer Printing",
      "Banner Printing",
      "Brochure Printing",
      "Poster Printing",
      "Sticker Printing",
      "T-shirt Printing",
      "Mug Printing",
      "Photocopying",
      "Lamination",
      "Binding Services",
      "Logo Design",
      "Graphic Design",
      "Digital Marketing Design",
    ],
  },
  {
    category: "Quran & Islamic Services",
    subcategories: [
      "Quran Tutoring",
      "Tajweed Teaching",
      "Hifz-e-Quran",
      "Islamic Studies",
      "Namaz Teaching",
      "Arabic Language",
      "Qirat Training",
      "Online Quran Classes",
      "Female Quran Teacher",
      "Kids Quran Classes",
      "Adult Quran Classes",
      "Ramadan Special Classes",
      "Islamic History",
      "Hadith Studies",
      "Fiqh Studies",
    ],
  },
  {
    category: "Music & Dance",
    subcategories: [
      "Guitar Lessons",
      "Piano Lessons",
      "Singing Lessons",
      "Tabla Lessons",
      "Harmonium Lessons",
      "Flute Lessons",
      "Classical Music",
      "Folk Music",
      "Bollywood Dance",
      "Classical Dance",
      "Hip Hop Dance",
      "Kids Dance Classes",
      "Wedding Dance Choreography",
      "Music Production",
      "DJ Training",
    ],
  },
  {
    category: "Mehendi Artist",
    subcategories: [
      "Bridal Mehendi",
      "Arabic Mehendi",
      "Pakistani Mehendi",
      "Indian Mehendi",
      "Simple Mehendi",
      "Party Mehendi",
      "Kids Mehendi",
      "Glitter Mehendi",
      "Stone Work Mehendi",
      "Traditional Designs",
      "Modern Designs",
      "Mehendi Classes",
      "Henna Tattoo",
      "White Mehendi",
      "Black Mehendi",
    ],
  },
  {
    category: "Fruit & Vegetable Delivery",
    subcategories: [
      "Fresh Fruits Delivery",
      "Fresh Vegetables Delivery",
      "Organic Produce",
      "Daily Delivery Service",
      "Weekly Package",
      "Monthly Package",
      "Seasonal Fruits",
      "Imported Fruits",
      "Dry Fruits",
      "Cut Fruits",
      "Fruit Baskets",
      "Salad Mix",
      "Juice Making Fruits",
      "Premium Quality",
      "Farm Fresh",
    ],
  },
  {
    category: "Water Supply",
    subcategories: [
      "Mineral Water Supply",
      "Tanker Water Supply",
      "Drinking Water Supply",
      "Emergency Water Supply",
      "Daily Water Supply",
      "Weekly Water Supply",
      "Bore Water Supply",
      "Water Tank Filling",
      "Bulk Water Supply",
      "Water Quality Testing",
    ],
  },
  {
    category: "Gas Cylinder",
    subcategories: [
      "LPG Gas Cylinder Delivery",
      "Gas Cylinder Refill",
      "New Connection",
      "Emergency Gas Supply",
      "Commercial Gas Supply",
      "Gas Stove Repair",
      "Gas Pipe Installation",
      "Gas Leak Detection",
      "Gas Regulator Repair",
      "Gas Safety Inspection",
    ],
  },
  {
    category: "Real Estate Services",
    subcategories: [
      "Property Dealer",
      "House for Rent",
      "House for Sale",
      "Flat for Rent",
      "Plot for Sale",
      "Commercial Property",
      "Property Valuation",
      "Property Documentation",
      "Legal Documentation",
      "Property Management",
      "Rental Agreement",
      "Property Inspection",
      "Real Estate Consultant",
      "Investment Advice",
      "Property Marketing",
    ],
  },
  {
    category: "Architect & Engineers",
    subcategories: [
      "House Design",
      "Building Design",
      "Interior Design",
      "3D Modeling",
      "Structural Design",
      "Electrical Design",
      "Plumbing Design",
      "Landscape Design",
      "Commercial Design",
      "Site Supervision",
      "Construction Estimate",
      "Project Management",
      "Building Approval",
      "NOC Services",
      "Renovation Planning",
    ],
  },
  {
    category: "Solar & Renewable Energy",
    subcategories: [
      "Solar Panel Installation",
      "Solar System Design",
      "Solar Maintenance",
      "Solar Inverter Installation",
      "Solar Battery Installation",
      "Net Metering",
      "Off-Grid Solar System",
      "On-Grid Solar System",
      "Hybrid Solar System",
      "Solar Water Heater",
      "Solar Street Lights",
      "Solar Consultation",
      "Energy Audit",
      "Solar Panel Cleaning",
      "Solar Repair Services",
    ],
  },
  {
    category: "Gym & Fitness Equipment",
    subcategories: [
      "Home Gym Setup",
      "Treadmill Repair",
      "Gym Equipment Installation",
      "Gym Equipment Maintenance",
      "Fitness Equipment Sales",
      "Used Equipment",
      "Gym Design",
      "Personal Training",
      "Yoga Classes",
      "Aerobics Classes",
      "Zumba Classes",
      "CrossFit Training",
      "Bodybuilding Coaching",
      "Diet Planning",
      "Weight Management",
    ],
  },
  {
    category: "Packers & Movers",
    subcategories: [
      "House Shifting",
      "Office Shifting",
      "Local Shifting",
      "Intercity Shifting",
      "Packing Services",
      "Unpacking Services",
      "Loading & Unloading",
      "Furniture Moving",
      "Safe & Secure Moving",
      "Vehicle Transportation",
      "Warehouse Storage",
      "International Moving",
      "Piano Moving",
      "Heavy Machinery Moving",
      "Fragile Items Moving",
    ],
  },
  {
    category: "Tent & Marquee Services",
    subcategories: [
      "Wedding Tent",
      "Party Tent",
      "Shamiana",
      "Pandal",
      "Canopy Rental",
      "Furniture Rental",
      "Stage Setup",
      "Lighting Arrangement",
      "Sound System",
      "Generator Service",
      "Catering Setup",
      "Decoration Services",
      "AC Tent",
      "Outdoor Events",
      "Corporate Events",
    ],
  },
  {
    category: "Pest & Fumigation",
    subcategories: [
      "Termite Treatment",
      "Bed Bugs Treatment",
      "Cockroach Control",
      "Mosquito Control",
      "Rat Control",
      "Lizard Control",
      "Ant Control",
      "Flies Control",
      "Fumigation Services",
      "Pre-Construction Treatment",
      "Post-Construction Treatment",
      "Warehouse Fumigation",
      "Restaurant Pest Control",
      "Hotel Pest Control",
      "Hospital Pest Control",
    ],
  },
  {
    category: "Fire & Safety Services",
    subcategories: [
      "Fire Extinguisher Installation",
      "Fire Alarm Installation",
      "Fire Safety Training",
      "Emergency Exit Setup",
      "Fire Fighting Equipment",
      "Smoke Detector Installation",
      "Fire Safety Inspection",
      "Fire Extinguisher Refilling",
      "Safety Signage",
      "Safety Equipment Supply",
      "Fire Risk Assessment",
      "Safety Consultation",
      "Emergency Lighting",
      "Fire Sprinkler System",
      "Fire Drill Training",
    ],
  },
];
