export  const services = [
    {
      category: "Electrician",
      subcategories: [
        "General Electrical Repairs",
        "AC Repair and Installation",
        "Electrical Panel Upgrades",
        "Smart Home Wiring",
        "Emergency Electrical Services",
        "Solar Panel Installation",
        "Generator Installation",
        "Home Theater Wiring",
        "Electrical Safety Inspection",
        "Circuit Breaker Installation",
        "Lighting Installation",
        "Outlet and Switch Installation",
        "Ceiling Fan Installation",
        "Wiring and Rewiring",
        "Electrical Appliance Repair",
      ],
    },
    {
      category: "Plumber",
      subcategories: [
        "Leak Detection and Repair",
        "Pipe Replacement",
        "Bathroom Plumbing Fixtures",
        "Water Tank Installation",
        "Septic Tank Cleaning",
        "Gas Pipe Installation",
        "Sump Pump Installation",
        "Hydro Jetting",
        "Bathroom Waterproofing",
        "Drain Cleaning",
        "Toilet Repair",
        "Faucet Repair",
        "Sewer Line Services",
        "Water Heater Repair",
        "Pipe Insulation",
      ],
    },
    {
      category: "Carpenter",
      subcategories: [
        "Custom Furniture Design",
        "Kitchen Cabinet Installation",
        "Wooden Flooring Installation",
        "Deck Construction",
        "Door Frame Repair",
        "Staircase Installation",
        "Wood Paneling",
        "Shelving Installation",
        "Furniture Restoration",
        "Wardrobe Installation",
        "Furniture Assembly",
        "Window Frame Repair",
        "Furniture Repair",
        "Wooden Fence Installation",
        "Office Furniture Installation",
      ],
    },
    {
      category: "Painter",
      subcategories: [
        "Interior Painting",
        "Exterior Painting",
        "Wall Texturing",
        "Wallpaper Installation",
        "Spray Painting",
        "Fence Painting",
        "Decorative Painting",
        "Epoxy Floor Coating",
        "Commercial Painting",
        "Faux Finishing",
        "Paint Removal",
        "Graffiti Removal",
        "Rust Proofing",
        "Eco-Friendly Painting",
        "Industrial Coatings",
      ],
    },
    {
      category: "Cleaning Services",
      subcategories: [
        "Home Deep Cleaning",
        "Carpet Cleaning",
        "Sofa Cleaning",
        "Office Cleaning",
        "Window Cleaning",
        "Pest Control",
        "Post-Construction Cleaning",
        "Move-in/Move-out Cleaning",
        "Pressure Washing",
        "Air Duct Cleaning",
        "Mattress Cleaning",
        "Pool Cleaning",
        "Curtain Cleaning",
        "Hoarding Cleanup",
        "Solar Panel Cleaning",
      ],
    },
    {
      category: "AC Technician",
      subcategories: [
        "AC Installation",
        "AC Repair",
        "AC Gas Refilling",
        "AC Maintenance",
        "Split AC Servicing",
        "Window AC Repair",
        "Thermostat Repair",
        "Ductless Mini-Split Installation",
        "Commercial AC Servicing",
        "Refrigerant Charging",
        "AC Filter Replacement",
        "AC Compressor Repair",
        "Emergency AC Repair",
        "AC Duct Cleaning",
        "AC Insulation Services",
      ],
    },
    {
      category: "Home Appliance Repair",
      subcategories: [
        "Refrigerator Repair",
        "Washing Machine Repair",
        "Microwave Repair",
        "Oven Repair",
        "Dishwasher Repair",
        "Dryer Repair",
        "Vacuum Cleaner Repair",
        "Coffee Machine Repair",
        "Blender Repair",
        "Toaster Repair",
        "Ice Maker Repair",
        "Home Theater Repair",
        "Fan Repair",
        "Water Purifier Repair",
        "Stove Repair",
      ],
    },
    {
      category: "Gardening & Landscaping",
      subcategories: [
        "Lawn Mowing",
        "Hedge Trimming",
        "Garden Design",
        "Tree Trimming",
        "Irrigation System Installation",
        "Planting Services",
        "Garden Pest Control",
        "Soil Fertilizing",
        "Garden Lighting",
        "Water Feature Installation",
        "Garden Pathway Construction",
        "Seasonal Planting",
        "Garden Waste Removal",
        "Garden Cleanup",
        "Landscape Consultation",
      ],
    },
    {
      category: "Roofing & Waterproofing",
      subcategories: [
        "Roof Repair",
        "Roof Replacement",
        "Waterproofing Services",
        "Gutter Cleaning",
        "Chimney Repair",
        "Skylight Installation",
        "Flashing Repair",
        "Balcony Waterproofing",
        "Flat Roof Repair",
        "Shingle Replacement",
        "Roof Inspection",
        "Roof Cleaning",
        "Insulation Installation",
        "Leak Repair",
        "Roof Coating",
      ],
    },
    {
      category: "Security Services",
      subcategories: [
        "CCTV Installation",
        "Alarm System Installation",
        "Security Guard Services",
        "Access Control Systems",
        "Biometric Systems",
        "Fire Alarm Installation",
        "Security Patrol Services",
        "Intercom Systems",
        "Motion Detector Installation",
        "Video Door Phone Installation",
        "Security System Maintenance",
        "Security Consultancy",
        "Security System Repair",
        "Access Card Setup",
        "Security Lighting Installation",
      ],
    },
    {
      category: "Laundry & Dry Cleaning",
      subcategories: [
        "Clothes Washing",
        "Dry Cleaning",
        "Ironing and Pressing",
        "Shoe Cleaning",
        "Curtain Cleaning",
        "Carpet Cleaning",
        "Leather Cleaning",
        "Blanket Cleaning",
        "Uniform Cleaning",
        "Stain Removal",
        "Delicate Fabric Care",
        "Alterations & Repairs",
        "Pick-up and Delivery",
        "Wedding Dress Cleaning",
        "Upholstery Cleaning",
      ],
    },
    {
      category: "Moving & Packing",
      subcategories: [
        "Local Moving",
        "Long-distance Moving",
        "Packing Services",
        "Unpacking Services",
        "Furniture Disassembly",
        "Furniture Assembly",
        "Storage Services",
        "Vehicle Transport",
        "Office Moving",
        "Fragile Item Handling",
        "Heavy Lifting",
        "Loading and Unloading",
        "International Moving",
        "Moving Supplies",
        "Disposal Services",
      ],
    },
    {
      category: "Pest Control",
      subcategories: [
        "Termite Treatment",
        "Bed Bug Extermination",
        "Mosquito Control",
        "Rodent Control",
        "Cockroach Treatment",
        "Ant Control",
        "Flea Control",
        "Spider Control",
        "Bee Removal",
        "Bird Control",
        "Pest Inspection",
        "Commercial Pest Control",
        "Organic Pest Control",
        "Pest Prevention",
        "Wasp Nest Removal",
      ],
    },
    {
      category: "Home Remodeling & Renovation",
      subcategories: [
        "Kitchen Remodeling",
        "Bathroom Renovation",
        "Flooring Installation",
        "Wall Partition",
        "False Ceiling",
        "Plumbing Renovation",
        "Electrical Renovation",
        "Painting and Decorating",
        "Tile Installation",
        "Cabinet Installation",
        "Door Replacement",
        "Window Replacement",
        "Basement Renovation",
        "Room Additions",
        "Outdoor Patio Construction",
      ],
    },
    {
      category: "HVAC Services",
      subcategories: [
        "Heating System Installation",
        "Heating System Repair",
        "Ventilation Cleaning",
        "Duct Installation",
        "Duct Repair",
        "HVAC Maintenance",
        "Thermostat Installation",
        "Furnace Repair",
        "Heat Pump Services",
        "Boiler Repair",
        "Indoor Air Quality Testing",
        "Energy Efficient Upgrades",
        "Commercial HVAC Services",
        "HVAC System Replacement",
        "Air Purifier Installation",
      ],
    },
    {
      category: "Interior Designing",
      subcategories: [
        "Space Planning",
        "Furniture Selection",
        "Lighting Design",
        "Color Consultation",
        "Window Treatments",
        "Flooring Selection",
        "Wall Decor",
        "Kitchen Design",
        "Bathroom Design",
        "Home Office Design",
        "Custom Furniture Design",
        "Storage Solutions",
        "Children's Room Design",
        "Home Staging",
        "Outdoor Living Space Design",
      ],
    },
    {
      category: "Appliance Installation",
      subcategories: [
        "Water Heater Installation",
        "Dishwasher Installation",
        "Oven Installation",
        "Ceiling Fan Installation",
        "Exhaust Fan Installation",
        "Washing Machine Installation",
        "Refrigerator Installation",
        "Microwave Installation",
        "Garbage Disposal Installation",
        "Dryer Installation",
        "Air Conditioner Installation",
        "Home Theater Setup",
        "Security Device Installation",
        "Smart Home Device Setup",
        "Solar Water Heater Installation",
      ],
    },
    {
      category: "Fitness & Health at Home",
      subcategories: [
        "Personal Training",
        "Yoga Instruction",
        "Massage Therapy",
        "Physiotherapy",
        "Nutrition Consultation",
        "Pilates Instruction",
        "Meditation Coaching",
        "Home Gym Setup",
        "Posture Correction",
        "Weight Loss Coaching",
        "Strength Training",
        "Cardio Training",
        "Injury Rehabilitation",
        "Senior Fitness",
        "Sports Coaching",
      ],
    },
    {
      category: "Technology & IT Support",
      subcategories: [
        "Computer Repair",
        "Printer Setup",
        "Network Setup",
        "Virus Removal",
        "Data Recovery",
        "Software Installation",
        "Hardware Upgrade",
        "Wi-Fi Optimization",
        "Smart Home Installation",
        "TV Mounting",
        "Home Theater Setup",
        "Security Software Setup",
        "Cloud Backup Setup",
        "Email Setup",
        "IT Consultation",
      ],
    },
    {
      category: "Pet Care",
      subcategories: [
        "Pet Grooming",
        "Veterinary Services",
        "Pet Sitting",
        "Dog Walking",
        "Pet Training",
        "Pet Boarding",
        "Pet Vaccination",
        "Pet Nutrition Consultation",
        "Pet Taxi",
        "Pet Bathing",
        "Pet Dental Care",
        "Pet Behavior Counseling",
        "Exotic Pet Care",
        "Pet Adoption Services",
        "Emergency Pet Care",
      ],
    },
    {
      category: "Event & Party Services",
      subcategories: [
        "Catering",
        "Photography",
        "Decoration",
        "DJ Services",
        "Tent Rental",
        "Chair and Table Rental",
        "Event Planning",
        "Sound System Setup",
        "Lighting Setup",
        "Video Recording",
        "Cake Design",
        "Invitation Design",
        "Security for Events",
        "Cleaning After Events",
        "Makeup and Hair Styling",
      ],
    },
    {
      category: "Automotive Services at Home",
      subcategories: [
        "Car Wash",
        "Car Detailing",
        "Minor Repairs",
        "Battery Replacement",
        "Tire Change",
        "Oil Change",
        "Car Polishing",
        "Engine Diagnostics",
        "Windshield Repair",
        "Headlight Restoration",
        "Brake Service",
        "Air Conditioning Service",
        "Car Interior Cleaning",
        "Fluid Top-Up",
        "Vehicle Inspection",
      ],
    },
    {
      category: "Tutoring & Education",
      subcategories: [
        "Language Tutoring",
        "Music Lessons",
        "Math Tutoring",
        "Science Tutoring",
        "Computer Lessons",
        "Exam Preparation",
        "Reading and Writing",
        "Art Lessons",
        "Dance Lessons",
        "Homework Help",
        "Test Taking Strategies",
        "Study Skills Coaching",
        "College Admissions Counseling",
        "Special Needs Tutoring",
        "Online Tutoring",
      ],
    },
    {
      category: "Legal & Financial Services",
      subcategories: [
        "Notary Services",
        "Tax Consultation",
        "Legal Advice",
        "Insurance Consulting",
        "Will Preparation",
        "Contract Drafting",
        "Business Registration",
        "Property Law Services",
        "Family Law Services",
        "Immigration Assistance",
        "Debt Counseling",
        "Investment Advice",
        "Loan Consulting",
        "Audit Services",
        "Mediation Services",
      ],
    },
    {
      category: "Miscellaneous",
      subcategories: [
        "Courier & Delivery",
        "Errand Running",
        "Personal Shopping",
        "Handyman Services",
        "Appliance Recycling",
        "Furniture Disposal",
        "Key Cutting",
        "Locksmith Services",
        "Custom Gifts",
        "Language Translation",
        "Meditation Coaching",
        "Personal Assistant",
        "Mobile Car Wash",
        "Recycling Pickup",
        "Volunteer Coordination",
      ],
    },
  ];
