export const ShopServices = [
  "Food & Grocery",
  "Clothing & Apparel",
  "Shoes & Footwear",
  "Bags & Accessories",
  "Electronics",
  "Mobile & Accessories",
  "Computer & Laptop Shops",
  "Furniture & Wood Work",
  "Home Decor",
  "Hardware & Tools",
  "Car Repair & Service",
  "Bike Repair & Service",
  "Auto Parts",
  "Pharmacy / Medical Store",
  "Books & Stationery",
  "Sports & Fitness",
  "Toys & Kids Items",
  "Jewelry & Watches",
  "Beauty & Cosmetics",
  "Barber Shop / Salon",
  "Tailor / Stitching",
  "Dry Cleaner / Laundry",
  "Gift Shop",
  "Pet Shop",
  "Flower Shop",
  "Agriculture / Seeds / Fertilizers",
  "Paint & Chemical Store",
  "Building Material",
  "Plumbing & Sanitary",
  "Electric Store",
  "Lighting & LED",
  "CCTV & Security Systems",
  "Bakery & Sweets",
  "Restaurant / Fast Food",
  "Tea & Coffee Shop",
  "Ice Cream / Juice Corner",
  "Meat Shop",
  "Fish Shop",
  "Vegetables & Fruits",
  "Dairy / Milk Shop",
  "Water & Beverages",
  "Photocopy / Printing Shop",
  "Travel Agency",
  "Real Estate",
  "Glass & Aluminum Work",
  "Auto Electrician",
  "Car Wash",
  "Gas & Cylinder Shop",
  "Mobile Repairing",
  "Laptop Repairing",
  "Shoe Repair",
  "Key Maker / Locksmith",
  "UPS / Solar / Battery Shop",
  "Medical Laboratory",
  "Clinic / Doctor",
  "Event Planner / Decorator",
  "Construction Services",
  "Painter / Electrician / Plumber",
  "Engineering Services",
  "Book Binding",
  "Street Food Vendor",
  "Textile & Fabric"
];
