export const ShopServices = [
  "Food & Grocery",
  "Clothing & Apparel",
  "Shoes & Footwear",
  "Bags & Accessories",
  "Electronics",
  "Mobile & Accessories",
  "Computer & Laptop Shops",
  "Furniture & Wood Work",
  "Home Decor",
  "Hardware & Tools",
  "Car Repair / Mechanic",
  "Bike Repair / Mechanic",
  "Auto Parts & Accessories",
  "Auto Service / Mechanic",
  "Bike Service / Mechanic",
  "Puncture",
  "Tire & Wheel Shop",
  "Car Accessories",
  "Bike Accessories",
  "Battery Shop",
  "Oil Change Service",
  "Pharmacy / Medical Store",
  "Books & Stationery",
  "Sports & Fitness",
  "Toys & Kids Items",
  "Jewelry & Watches",
  "Beauty & Cosmetics",
  "Barber Shop / Salon",
  "Tailor / Stitching",
  "Dry Cleaner / Laundry",
  "Gift Shop",
  "Pet Shop",
  "Flower Shop",
  "Agriculture / Seeds / Fertilizers",
  "Paint & Chemical Store",
  "Building Material",
  "Plumbing & Sanitary",
  "Electric Store",
  "Lighting & LED",
  "CCTV & Security Systems",
  "Bakery & Sweets",
  "Restaurant / Fast Food",
  "Tea & Coffee Shop",
  "Ice Cream / Juice Corner",
  "Meat Shop",
  "Fish Shop",
  "Vegetables & Fruits",
  "Dairy / Milk Shop",
  "Water & Beverages",
  "Photocopy / Printing Shop",
  "Travel Agency",
  "Real Estate",
  "Petrol / CNG Station",
  "Glass & Aluminum Work",
  "Auto Electrician / Mechanic",
  "Car Wash & Detailing",
  "Gas & Cylinder Shop",
  "Mobile Repairing",
  "Laptop Repairing",
  "Shoe Repair",
  "Key Maker / Locksmith",
  "UPS / Solar / Battery Shop",
  "Medical Laboratory",
  "Clinic / Doctor",
  "Event Planner / Decorator",
  "Construction Services",
  "Painter / Electrician / Plumber",
  "Engineering Services",
  "Book Binding",
  "Street Food Vendor",
  "Textile & Fabric",
  "AC Repair & Service",
  "Refrigerator Repair",
  "TV Repair",
  "Washing Machine Repair",
  "Inverter & Stabilizer",
  "Generator Services",
  "Welding Shop",
  "Carpentry Services",
  "Marble & Tiles Shop",
  "Ceramics & Sanitary Ware",
  "Curtain & Blinds",
  "Mattress & Bedding",
  "Kitchen Utensils",
  "Crockery & Cutlery",
  "Plastic Items Shop",
  "Steel & Aluminum Utensils",
  "Packaging Materials",
  "Party Supplies",
  "Optician / Eyewear",
  "Hearing Aid Shop",
  "Dental Clinic",
  "Physiotherapy Center",
  "Gym & Fitness Center",
  "Yoga & Meditation Center",
  "Music & Instrument Shop",
  "Art & Craft Supplies",
  "Photography Studio",
  "Video & Photo Editing",
  "Advertising Agency",
  "Digital Printing",
  "Flex & Banner Printing",
  "Interior Design Services",
  "Architect Services",
  "Legal Services / Lawyer",
  "CA / Accountant Services",
  "Insurance Services",
  "Banking Services",
  "Money Transfer / Exchange",
  "Courier & Cargo Services",
  "Packers & Movers",
  "Car Rental",
  "Bike Rental",
  "Hotel & Guest House",
  "Catering Services",
  "Tent & Decoration",
  "Sound & DJ Services",
  "Marriage Bureau",
  "Astrology Services",
  "Religious Items Shop",
  "Car Parking Services",
  "Driving School",
  "Computer Training Institute",
  "Tuition Center / Academy",
  "Language Classes",
  "Security Services",
  "Cleaning Services",
  "Pest Control",
  "Gardening Services",
  "Pool & Aquarium Shop",
  "Bicycle Shop",
  "Motorcycle Showroom",
  "Car Showroom",
  "Scrap & Junk Dealer",
  "Recycling Services",
  "Woodworking & Sawmill",
  "Blacksmith / Iron Works",
  "Roof & Waterproofing",
  "False Ceiling Works",
  "POP & Gypsum Works",
  "Bamboo & Cane Work",
  "Handicrafts Shop",
  "Antique Shop",
  "Second Hand Shop",
  "Pawn Shop",
  "ATM Services",
  "Post Office Services",
];
